### ISSUE TITLE
api call to "List the authenticated users flattrs" => response is empty array

### ISSUE THREAD

**Issue by wrunkel** [flattr/developers.flattr.net#5]
hello 

i have a little trouble receiving a list of users flattres: 'List the authenticated users flattrs'

If i make a call to the api endpoint '/user/flattrs' i get a 200 Ok response with an empty array.
The request header contains the option (Authorization: 'Bearer xxxxxx...') witch worked fine so far for flattering a podcast etc. 

i know the documentation quotes: 
"If the response header is 200 OK but the response is empty there is two possible reasons. One is that the user have choosen to hide what he/she flattrs. The other is because that user haven't flattred anything yet."

but with my test user, i flatterd a few things and can see them in the: "Flattr Dashboard" and i can't find an option to show/hide what i flattred ...

So is there something i am making wrong ?

**Comment by leihog** [comment]
Hi,

You aren't doing anything wrong. This documentation is deprecated and the API itself is mostly defunct. Which is why neither of them are publicly available on flattr.com anymore.

**Comment by wrunkel** [comment]
Hi,

thx, so how would it be possible to list users flattrs and unflattr users flattred items ?

are there functional endpoints available for that ?

regards 

Wanja

**Comment by leihog** [comment]
Sorry, it's no longer possible though the API. :(

**Comment by wrunkel** [comment]
Thanks all right, thanks for the info :/
